Fix then_else macro
est31/postfix-macros pull request #9
Opened 2021-02-24 16:26 UTC by benediktwerner

After realizing the doc test passes I'm not sure anymore whether this is actually wrong or it's intended this way? But anyway, here it goes:

```rust
use postfix_macros::{postfix_macros, then, then_else};

fn main() {
    postfix_macros! {
        for i in 0..4 {
            (i % 2 == 0)
                .then!{ println!("{} - then", i) }
                .then_else!{ println!("{} - else", i) }
        }
    }
}
```

prints

```
0 - then
0 - else
1 - else
2 - then
2 - else
3 - else
```

Since `then_else` is supposed to be the equivalent of `else` I'd expect it to only ever print `then` or `else`. Instead, the `else` case always executes. The doc test is written as if this behavior is correct but that doesn't make any sense to me. I see no reason for a postfix macro that just runs the given code?

Looking at the macro definition this behavior completely makes sense. It doesn't actually involve an `else` anywhere. It just wraps the body in a block.

Since `postfix_macros!` wraps the `self` parameter in a block we can't actually just add an `else` and need to match on `then!` instead but that's probably a good thing since it avoids misuse of the macro. And I don't think there's any reason anybody would want to use this without `postfix_macros!` anyway.

I also added some more simple tests for all the built-in macros.

2021-02-24 19:01 UTC, est31 commented
Thanks for this good catch! I guess I made a mistake both in writing the macro as well as in writing the doctest.

2021-02-24 19:05 UTC, est31 requested changes
Good for the most part. Also thanks for adding tests!

2021-02-24 19:05 UTC, est31 commented on src/lib.rs
> +	({ then! ( $cond:expr, $($if_body:tt)* ) }, $($body:tt)*) => {
Could you do `$crate::then` here? It's not always certain the `then` macro is in scope.

2021-02-24 19:05 UTC, est31 commented on src/lib.rs
> +		else {
Could you put the else on the same line as the `}`?

2021-02-24 19:05 UTC, est31 commented on src/lib.rs
> +		else {
Same here

2021-02-28 23:33 UTC, benediktwerner commented
Sorry for taking a while to respond, I adjusted the formatting but regarding the `$crate::then`, I don't think that works or is an issue? It's pattern matching on the ident `then`, not using the macro.

2021-03-01 02:14 UTC, est31 commented
@benediktwerner that's a fair point.

2021-03-01 02:14 UTC, est31 approved these changes

2021-03-01 02:15 UTC, merged